### ISSUE TITLE
restart nginx

### ISSUE THREAD

**Issue by exrat** [xavier84/RatXaBox#1]
Salut
je pense qu'il te manque un restart de nginx avant la ligne 776 qui exécute logserver.sh
```
FONCSERVICE restart nginx
sh "$SCRIPT"/logserver.sh
```
actuellement la box est ko en fin d'install' (sans plex/emby => choix 3) + erreurs en console à la fin:
```
cp: impossible d'évaluer « /var/log/nginx/rutorrent-access.log »: Aucun fichier ou dossier de ce type
sed: impossible de lire access.log: Aucun fichier ou dossier de ce type
sed: impossible de lire access.log: Aucun fichier ou dossier de ce type
sed: impossible de lire access.log: Aucun fichier ou dossier de ce type
sed: impossible de lire access.log: Aucun fichier ou dossier de ce type
/usr/share/scripts-perso/logserver.sh: ligne 18: /tmp/access.log: Aucun fichier ou dossier de ce type
```
et ça rentre dans l'ordre pour rutorrent avec un restart à la main, donc regarde de ce coté là je pense.
Ex.

**Comment by xavier84** [comment]
Salut a toi!
merci pour ce petit bug (mince je sais pas comment je me suis débrouillé pour pas voir ça quand j'ai fais mes test)
donc il y a un restart de nginx sur la partie cp de dhparams.pem.
mais comme le vhost est pas finis (include)du coup il ne démarrait pas,
`nginx: [emerg] open() "/etc/nginx/conf.d/sickrage.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/rutorrent.conf:92` 
effectivement il faut avoir rutorrent-access.log pour générer les log en html.
du coup j'ai mis le start juste après la config des vhost de SR et CP
merci pour ce bug!
ps:bizarre j'ai pas recu de mail pour 'issues' que tu m'as fais.si j'etait pas venue sur github j’aurais pas vu ton issues.
merci beaucoup pour les conseil que tu me donne. :)

bonne journée
